# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [1]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [4]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.datasets import load_iris
iris = load_iris()
type(iris)

sklearn.utils.Bunch

## Question 2

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [7]:
X = iris.data

In [8]:
y = iris.target

In [9]:
X.shape

(150, 4)

In [10]:
np.unique(y)

array([0, 1, 2])

There are 150 rows and 4 columns. 3 labels in target column.

## New Section

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=112)
print(x_train.shape)
print(x_test.shape)

(112, 4)
(38, 4)


## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [12]:
en_y_train = tf.keras.utils.to_categorical(y_train,num_classes=3)
en_y_test = tf.keras.utils.to_categorical(y_test,num_classes=3)


In [13]:
en_y_train[0:5,:]

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [14]:
en_y_test[0:5,:]

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [15]:
model = tf.keras.models.Sequential()


## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [16]:
model.add(tf.keras.layers.Dense(3, activation='softmax', input_shape=(4,)))

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [18]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics='accuracy')

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


There are 4 neurons in input layer and final layer has 3 labels and hence 
4 * 3 = 12 
There will be 3 biases hence param# is **15**

## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [20]:
model.fit(x_train, en_y_train, 
          validation_data=(x_test, en_y_test), 
          epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 145ms/step - loss: 2.6563 - accuracy: 0.3844 - val_loss: 2.2931 - val_accuracy: 0.2105
Epoch 2/100
4/4 [==============================] - 0s 14ms/step - loss: 1.6607 - accuracy: 0.3932 - val_loss: 1.6516 - val_accuracy: 0.1842
Epoch 3/100
4/4 [==============================] - 0s 13ms/step - loss: 1.3731 - accuracy: 0.3452 - val_loss: 1.3742 - val_accuracy: 0.1053
Epoch 4/100
4/4 [==============================] - 0s 12ms/step - loss: 1.2455 - accuracy: 0.1568 - val_loss: 1.2513 - val_accuracy: 0.2105
Epoch 5/100
4/4 [==============================] - 0s 14ms/step - loss: 1.2263 - accuracy: 0.1693 - val_loss: 1.2227 - val_accuracy: 0.3158
Epoch 6/100
4/4 [==============================] - 0s 13ms/step - loss: 1.1448 - accuracy: 0.3536 - val_loss: 1.1637 - val_accuracy: 0.2895
Epoch 7/100
4/4 [==============================] - 0s 13ms/step - loss: 1.1249 - accuracy: 0.2830 - val_loss: 1.1133 - val_accuracy: 0.3421
Epoch 8/100
4/4 [==

epoc1 started with 90 training accuracy and 97 test accuracy, for epoch 100 training accuracy was increased to 93 and training accuracy is 97. The difference b/w train and test accuracy was reduced. Training more with many epocs and introducing additional layers and neurons ie with more hyperparm tuning accuracy will improve.

## Question 10

### Make predictions
- Predict labels on one row

In [21]:
input_data = np.expand_dims(x_test[0], axis=0)
input_data.shape

(1, 4)

In [22]:
model.predict(input_data)

array([[0.9079893 , 0.05809062, 0.03392002]], dtype=float32)

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [23]:
en_y_test[0]

array([1., 0., 0.], dtype=float32)

The first example of test data actual is label 0 and predicted also label 0. 



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [26]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [27]:
import tensorflow as tf
print(tf.__version__)

2.4.1


### Set random seed

In [28]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [29]:
# run this cell to upload file if you are using google colab
#from google.colab import files
#files.upload()

In [30]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/prices.csv')

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [31]:
df = df.drop(labels=['date','symbol'],axis=1)

In [32]:
df.shape

(851264, 5)

In [33]:
df.columns

Index(['open', 'close', 'low', 'high', 'volume'], dtype='object')

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [34]:
data = df.head(1000)

In [35]:
data.shape

(1000, 5)

## Question 4

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [36]:
X = data[["open", "close", "low", "high"]]
y = data[['volume']]/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"

In [37]:
#X = np.asarray(X).astype('float32')

In [38]:
X = np.asarray(X,dtype='float32')
y = np.asarray(y,dtype='float32')

## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [39]:
X[0:5,:]

array([[123.43, 125.84, 122.31, 126.25],
       [125.24, 119.98, 119.94, 125.54],
       [116.38, 114.95, 114.93, 119.74],
       [115.48, 116.62, 113.5 , 117.44],
       [117.01, 114.97, 114.09, 117.33]], dtype=float32)

In [40]:
X = tf.math.l2_normalize(X)

In [41]:
X[0:5,:]

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0.02202893, 0.02245905, 0.02182904, 0.02253223],
       [0.02235197, 0.0214132 , 0.02140606, 0.02240551],
       [0.0207707 , 0.02051548, 0.02051191, 0.02137037],
       [0.02061007, 0.02081353, 0.0202567 , 0.02095988],
       [0.02088314, 0.02051905, 0.020362  , 0.02094025]], dtype=float32)>

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [42]:
w = tf.zeros([4,1])
b = tf.zeros([1])

In [43]:
w,b

(<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[0.],
        [0.],
        [0.],
        [0.]], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>)

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [44]:
def prediction(X,W,b):
  return tf.add(tf.matmul(X,W),b)

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [45]:
def calcloss(act,pred):
   diff = act - pred
   sqr = tf.square(diff)
   loss = tf.reduce_mean(sqr)
   return loss
    

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [46]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = calcloss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias - Gradient Descent
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [47]:
#Train for 100 Steps
for i in range(200):
    
    w, b = train(X, y, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          calcloss(y, prediction(X, w, b)).numpy())

Current Loss on iteration 0 236.16805
Current Loss on iteration 1 235.09369
Current Loss on iteration 2 234.06194
Current Loss on iteration 3 233.07103
Current Loss on iteration 4 232.11937
Current Loss on iteration 5 231.20546
Current Loss on iteration 6 230.32774
Current Loss on iteration 7 229.4848
Current Loss on iteration 8 228.67522
Current Loss on iteration 9 227.89775
Current Loss on iteration 10 227.15106
Current Loss on iteration 11 226.43399
Current Loss on iteration 12 225.7453
Current Loss on iteration 13 225.08392
Current Loss on iteration 14 224.44872
Current Loss on iteration 15 223.83868
Current Loss on iteration 16 223.25284
Current Loss on iteration 17 222.69019
Current Loss on iteration 18 222.14981
Current Loss on iteration 19 221.6309
Current Loss on iteration 20 221.1325
Current Loss on iteration 21 220.65384
Current Loss on iteration 22 220.19417
Current Loss on iteration 23 219.75272
Current Loss on iteration 24 219.32877
Current Loss on iteration 25 218.92157


After one point of iterration the loss was having a very small increment to 209. With more hyperparm tuning we can even reduce loss.

### Observe values of Weight
- Print the updated values

In [48]:
w

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-0.00866881],
       [-0.00822744],
       [-0.00831046],
       [-0.00848581]], dtype=float32)>

### Observe values of Bias
- Print the updated values

In [49]:
b

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.220549], dtype=float32)>